### ISSUE TITLE
High level ToDo list

### ISSUE THREAD

**Issue by serolrom** [serolrom/HomeFlightSimulator_EN#9]
- [ ] Bajar mesa de costura al salón: mueble preliminar
- [ ] Testear mesa de costura con el monitor: mudanza preliminar
- [ ] Bajar programa de edición 3D para plantear diseño del sim en el salón
- [ ] Seguir definiendo siguientes pasos
